version: '2'

volumes:
  db-data:
    external: false

services:
  db:
    image: jadsonlourenco/mongo-rocks
    # volumes:
    #   - db-data:/usr/local/pgsql/data
  es:
    image: elasticsearch:2.0
  redis:
    image: redis
  sidekiq:
    build: .
    command: bundle exec sidekiq -C ./config/sidekiq.yml
    depends_on:
      - db
      - redis
    volumes:
      - .:/elvis
    environment:
      - RAILS_ENV=production
      - RACK_ENV=production
  api:
    build: .
    volumes:
      - .:/elvis
    environment:
      - RAILS_ENV=production
      - RACK_ENV=production
    ports:
      - "3000:3000"
    depends_on:
      - es
      - db
      - redis
      - sidekiq
    links:
      - es
      - db
      - redis
      - sidekiq
